#!/usr/bin/env python3
"""Generate Python rule files from YAML schemas.

Reads the YAML files from rules/generated/ and produces the Python files
in src/rules/. Generated files include an auto-generation header comment.

Usage:
    python scripts/generate_rules.py              # Regenerate all rule files
    python scripts/generate_rules.py --check      # Check if files are up to date
"""

import argparse
import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
GENERATED_DIR = PROJECT_ROOT / "rules" / "generated"
RULES_DIR = PROJECT_ROOT / "src" / "rules"

HEADER_TEMPLATE = '''\
# THIS FILE IS AUTO-GENERATED from rules/generated/{yaml_file}
# DO NOT EDIT MANUALLY. Run `python scripts/generate_rules.py` to regenerate.
# Source: Visa Core Rules {version}
'''


def load_yaml(name: str) -> dict:
    """Load a YAML file from the generated directory."""
    path = GENERATED_DIR / f"{name}.yaml"
    if not path.exists():
        print(f"Error: {path} not found.", file=sys.stderr)
        sys.exit(1)
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def header(yaml_file: str, version: str) -> str:
    """Generate the auto-generation header comment."""
    return HEADER_TEMPLATE.format(yaml_file=yaml_file, version=version)


def generate_time_limits() -> str:
    """Generate src/rules/time_limits.py from time_limits.yaml."""
    data = load_yaml("time_limits")
    version = data.get("version", "unknown")
    lines = [header("time_limits.yaml", version)]

    lines.append('"""Time limit calculations for Visa dispute conditions.')
    lines.append("")
    lines.append("Encodes the specific time limits from Visa Core Rules Section 11 for each")
    lines.append("dispute condition, including regional exceptions.")
    lines.append('"""')
    lines.append("")
    lines.append("from datetime import date, datetime, timedelta")
    lines.append("")
    lines.append("from src.models.dispute import TimeLimit")
    lines.append("from src.models.enums import DisputeCondition, Region")
    lines.append("")
    lines.append("DateLike = date | datetime")
    lines.append("")

    # DISPUTE_TIME_LIMITS
    lines.append("# Time limits encoded from Visa Core Rules Section 11")
    lines.append("# Each condition has a base time limit and optional regional exceptions")
    lines.append("DISPUTE_TIME_LIMITS: dict[DisputeCondition, TimeLimit] = {")

    condition_enum_map = _condition_enum_map()
    for cond_code, tl in data["dispute_time_limits"].items():
        enum_name = condition_enum_map.get(cond_code)
        if enum_name is None:
            continue
        region_ex = tl.get("region_exceptions", {})
        region_str = repr(region_ex) if region_ex else ""
        lines.append(f"    DisputeCondition.{enum_name}: TimeLimit(")
        lines.append(f"        calendar_days={tl['calendar_days']},")
        lines.append(f'        from_event="{tl["from_event"]}",')
        if region_ex:
            lines.append(f"        region_exceptions={region_str},")
        lines.append(f'        description="{tl["description"]}",')
        lines.append("    ),")

    lines.append("}")
    lines.append("")

    # PRE_ARBITRATION_TIME_LIMITS
    lines.append("# Pre-arbitration time limits by dispute category flow")
    lines.append('PRE_ARBITRATION_TIME_LIMITS: dict[str, TimeLimit] = {')
    for flow_name, tl in data["pre_arbitration_time_limits"].items():
        region_ex = tl.get("region_exceptions", {})
        lines.append(f'    "{flow_name}": TimeLimit(')
        lines.append(f"        calendar_days={tl['calendar_days']},")
        lines.append(f'        from_event="{tl["from_event"]}",')
        if region_ex:
            lines.append(f"        region_exceptions={repr(region_ex)},")
        lines.append(f'        description="{tl["description"]}",')
        lines.append("    ),")
    lines.append("}")
    lines.append("")

    # ARBITRATION_TIME_LIMIT
    arb = data["arbitration_time_limit"]
    lines.append("# Arbitration time limit (same for all categories)")
    lines.append("ARBITRATION_TIME_LIMIT = TimeLimit(")
    lines.append(f"    calendar_days={arb['calendar_days']},")
    lines.append(f'    from_event="{arb["from_event"]}",')
    lines.append(f'    description="{arb["description"]}",')
    lines.append(")")
    lines.append("")

    # Functions
    lines.append("")
    lines.append("def calculate_deadline(")
    lines.append("    event_date: DateLike,")
    lines.append("    condition: DisputeCondition,")
    lines.append("    region: Region = Region.GLOBAL,")
    lines.append(") -> DateLike:")
    lines.append('    """Calculate the deadline for filing a dispute.')
    lines.append("")
    lines.append("    Per Section 11.2.1: For the purpose of calculating a dispute-related")
    lines.append("    timeframe, the Processing Date of the preceding event is not counted")
    lines.append("    as one day.")
    lines.append('    """')
    lines.append("    time_limit = DISPUTE_TIME_LIMITS.get(condition)")
    lines.append("    if time_limit is None:")
    lines.append('        raise ValueError(f"No time limit defined for condition {condition.value}")')
    lines.append("")
    lines.append("    days = time_limit.calendar_days")
    lines.append("    # The processing date itself is NOT counted (per 11.2.1)")
    lines.append("    return event_date + timedelta(days=days + 1)")
    lines.append("")
    lines.append("")
    lines.append("def _to_date(d: DateLike) -> date:")
    lines.append('    """Normalize a date or datetime to a plain date for comparison."""')
    lines.append("    if isinstance(d, datetime):")
    lines.append("        return d.date()")
    lines.append("    return d")
    lines.append("")
    lines.append("")
    lines.append("def is_within_time_limit(")
    lines.append("    event_date: DateLike,")
    lines.append("    filing_date: DateLike,")
    lines.append("    condition: DisputeCondition,")
    lines.append("    region: Region = Region.GLOBAL,")
    lines.append(") -> bool:")
    lines.append('    """Check if a dispute filing is within the allowed time limit."""')
    lines.append("    deadline = calculate_deadline(event_date, condition, region)")
    lines.append("    return _to_date(filing_date) <= _to_date(deadline)")
    lines.append("")
    lines.append("")
    lines.append("def get_pre_arbitration_deadline(")
    lines.append("    preceding_event_date: datetime,")
    lines.append("    category_flow: str,")
    lines.append("    region: Region = Region.GLOBAL,")
    lines.append("    is_atm: bool = False,")
    lines.append("    is_domestic: bool = False,")
    lines.append("    country: str | None = None,")
    lines.append(") -> datetime:")
    lines.append('    """Calculate the pre-arbitration deadline with regional exceptions."""')
    lines.append('    time_limit = PRE_ARBITRATION_TIME_LIMITS.get(category_flow)')
    lines.append("    if time_limit is None:")
    lines.append('        raise ValueError(f"No pre-arbitration time limit for flow: {category_flow}")')
    lines.append("")
    lines.append("    days = time_limit.calendar_days")
    lines.append("")
    lines.append("    # Apply regional exceptions")
    lines.append("    if region == Region.CEMEA and is_domestic:")
    lines.append('        if country == "nigeria":')
    lines.append('            exception_key = "cemea_nigeria"')
    lines.append("            if exception_key in time_limit.region_exceptions:")
    lines.append("                days = time_limit.region_exceptions[exception_key]")
    lines.append('        elif country == "tanzania":')
    lines.append('            exception_key = "cemea_tanzania"')
    lines.append("            if exception_key in time_limit.region_exceptions:")
    lines.append("                days = time_limit.region_exceptions[exception_key]")
    lines.append('        elif country == "egypt" and is_atm:')
    lines.append('            exception_key = "cemea_egypt_atm"')
    lines.append("            if exception_key in time_limit.region_exceptions:")
    lines.append("                days = time_limit.region_exceptions[exception_key]")
    lines.append("")
    lines.append('    if region == Region.EUROPE and country == "poland" and is_atm:')
    lines.append('        exception_key = "europe_poland_atm"')
    lines.append("        if exception_key in time_limit.region_exceptions:")
    lines.append("            days = time_limit.region_exceptions[exception_key]")
    lines.append("")
    lines.append('    if region == Region.AP and is_domestic and is_atm and country == "india":')
    lines.append('        exception_key = "ap_india_atm"')
    lines.append("        if exception_key in time_limit.region_exceptions:")
    lines.append("            days = time_limit.region_exceptions[exception_key]")
    lines.append("")
    lines.append("    return preceding_event_date + timedelta(days=days + 1)")
    lines.append("")
    lines.append("")
    lines.append("def get_arbitration_deadline(pre_arb_response_date: datetime) -> datetime:")
    lines.append('    """Calculate the arbitration filing deadline.')
    lines.append("")
    lines.append("    10 calendar days from the Processing Date of the pre-Arbitration response.")
    lines.append('    """')
    lines.append("    return pre_arb_response_date + timedelta(days=ARBITRATION_TIME_LIMIT.calendar_days + 1)")
    lines.append("")

    return "\n".join(lines)


def generate_validity() -> str:
    """Generate src/rules/validity.py from validity.yaml."""
    data = load_yaml("validity")
    version = data.get("version", "unknown")
    lines = [header("validity.yaml", version)]

    lines.append('"""Dispute validity checking logic.')
    lines.append("")
    lines.append("Data-driven validity checker loaded from rules/generated/validity.yaml.")
    lines.append("Each dispute condition has specific circumstances that make a dispute invalid.")
    lines.append('"""')
    lines.append("")
    lines.append("from dataclasses import dataclass")
    lines.append("from datetime import datetime")
    lines.append("from pathlib import Path")
    lines.append("from typing import Any")
    lines.append("")
    lines.append("import yaml")
    lines.append("")
    lines.append("from src.models.dispute import DisputeCase, RuleEvaluationResult")
    lines.append("from src.models.enums import DisputeCondition")
    lines.append("")
    lines.append("")
    lines.append("@dataclass")
    lines.append("class ValidityCheckResult:")
    lines.append('    """Result of a dispute validity check."""')
    lines.append("")
    lines.append("    is_valid: bool")
    lines.append("    reason: str")
    lines.append("    rule_section: str")
    lines.append("    condition_checked: str")
    lines.append("")
    lines.append("")
    lines.append("# Load validity rules from YAML at import time")
    lines.append('_YAML_PATH = Path(__file__).resolve().parent.parent.parent / "rules" / "generated" / "validity.yaml"')
    lines.append("with open(_YAML_PATH, encoding=\"utf-8\") as _f:")
    lines.append("    _VALIDITY_DATA: dict[str, Any] = yaml.safe_load(_f)")
    lines.append('_CONDITIONS: dict[str, Any] = _VALIDITY_DATA.get("conditions", {})')
    lines.append("")
    lines.append("")
    lines.append("def _resolve_field(obj: Any, field_path: str) -> Any:")
    lines.append('    """Traverse dotted paths on Pydantic models or dicts."""')
    lines.append('    parts = field_path.split(".")')
    lines.append("    current = obj")
    lines.append("    for part in parts:")
    lines.append("        if current is None:")
    lines.append("            return None")
    lines.append("        if isinstance(current, dict):")
    lines.append("            current = current.get(part)")
    lines.append("        else:")
    lines.append("            current = getattr(current, part, None)")
    lines.append("    return current")
    lines.append("")
    lines.append("")
    lines.append("def _evaluate_rule(case: DisputeCase, rule: dict[str, Any], rule_section: str) -> ValidityCheckResult | None:")
    lines.append('    """Evaluate a single validity rule against a case. Returns a result if the rule triggers."""')
    lines.append('    field_path = rule["field"]')
    lines.append('    reason = rule["reason"]')
    lines.append("    value = _resolve_field(case, field_path)")
    lines.append("")
    lines.append("    # Handle different comparison operators")
    lines.append('    if "equals" in rule:')
    lines.append('        expected = rule["equals"]')
    lines.append("")
    lines.append("        # Handle enum values - compare by .value if available")
    lines.append("        actual = value.value if hasattr(value, 'value') else value")
    lines.append("")
    lines.append('        if actual != expected:')
    lines.append("            return None")
    lines.append("")
    lines.append("        # Check additional constraints if present")
    lines.append('        if "additional_field" in rule:')
    lines.append('            add_value = _resolve_field(case, rule["additional_field"])')
    lines.append("            add_actual = add_value.value if hasattr(add_value, 'value') else add_value")
    lines.append('            if "additional_equals_any" in rule:')
    lines.append('                if add_actual not in rule["additional_equals_any"]:')
    lines.append("                    return None")
    lines.append('            if "additional_not_equals" in rule:')
    lines.append('                if add_actual == rule["additional_not_equals"]:')
    lines.append("                    return None")
    lines.append("")
    lines.append('    elif "not_equals" in rule:')
    lines.append('        expected = rule["not_equals"]')
    lines.append("        actual = value.value if hasattr(value, 'value') else value")
    lines.append("        if actual == expected:")
    lines.append("            return None")
    lines.append("")
    lines.append('    elif "starts_with" in rule:')
    lines.append("        if value is None or not str(value).startswith(rule[\"starts_with\"]):")
    lines.append("            return None")
    lines.append("")
    lines.append('    elif "is_truthy" in rule:')
    lines.append("        if not value:")
    lines.append("            return None")
    lines.append("")
    lines.append('    elif "is_empty" in rule:')
    lines.append("        if value:")
    lines.append("            return None")
    lines.append("")
    lines.append("    else:")
    lines.append("        return None")
    lines.append("")
    lines.append("    # Build a condition_checked identifier from the field path")
    lines.append('    condition_checked = field_path.split(".")[-1]')
    lines.append("")
    lines.append("    return ValidityCheckResult(")
    lines.append("        is_valid=False,")
    lines.append("        reason=reason,")
    lines.append("        rule_section=rule_section,")
    lines.append("        condition_checked=condition_checked,")
    lines.append("    )")
    lines.append("")
    lines.append("")
    lines.append("def check_validity(case: DisputeCase, condition: DisputeCondition) -> list[ValidityCheckResult]:")
    lines.append('    """Check validity of a dispute using data-driven rules from YAML.')
    lines.append("")
    lines.append("    Args:")
    lines.append("        case: The dispute case to evaluate.")
    lines.append("        condition: The dispute condition to check against.")
    lines.append("")
    lines.append("    Returns:")
    lines.append("        List of validity check results.")
    lines.append('    """')
    lines.append("    cond_data = _CONDITIONS.get(condition.value)")
    lines.append("    if cond_data is None:")
    lines.append("        return [")
    lines.append("            ValidityCheckResult(")
    lines.append("                is_valid=True,")
    lines.append('                reason=f"No specific validity checker for {condition.value}; default valid",')
    lines.append('                rule_section="11.6",')
    lines.append('                condition_checked="default_pass",')
    lines.append("            )")
    lines.append("        ]")
    lines.append("")
    lines.append('    rule_section = cond_data["rule_section"]')
    lines.append('    invalid_rules = cond_data.get("invalid_when", [])')
    lines.append("    results: list[ValidityCheckResult] = []")
    lines.append("")
    lines.append("    for rule in invalid_rules:")
    lines.append("        result = _evaluate_rule(case, rule, rule_section)")
    lines.append("        if result is not None:")
    lines.append("            results.append(result)")
    lines.append("")
    lines.append("    if not results:")
    lines.append("        results.append(")
    lines.append("            ValidityCheckResult(")
    lines.append("                is_valid=True,")
    lines.append('                reason=f"No invalid conditions found for {condition.value}",')
    lines.append("                rule_section=rule_section,")
    lines.append('                condition_checked="all_checks_passed",')
    lines.append("            )")
    lines.append("        )")
    lines.append("")
    lines.append("    return results")
    lines.append("")
    lines.append("")
    lines.append("def check_dispute_validity(case: DisputeCase) -> list[ValidityCheckResult]:")
    lines.append('    """Run all applicable validity checks for a dispute case.')
    lines.append("")
    lines.append("    Returns a list of validity check results. If any result has is_valid=False,")
    lines.append("    the dispute is considered invalid under that condition.")
    lines.append('    """')
    lines.append("    if case.condition is None:")
    lines.append("        return [")
    lines.append("            ValidityCheckResult(")
    lines.append("                is_valid=False,")
    lines.append('                reason="No dispute condition assigned",')
    lines.append('                rule_section="11.6",')
    lines.append('                condition_checked="condition_assignment",')
    lines.append("            )")
    lines.append("        ]")
    lines.append("")
    lines.append("    return check_validity(case, case.condition)")
    lines.append("")
    lines.append("")
    lines.append("def convert_to_rule_evaluation(result: ValidityCheckResult) -> RuleEvaluationResult:")
    lines.append('    """Convert a validity check result to a rule evaluation result for recording."""')
    lines.append("    return RuleEvaluationResult(")
    lines.append('        rule_id=f"validity_{result.condition_checked}",')
    lines.append("        rule_section=result.rule_section,")
    lines.append("        rule_description=result.reason,")
    lines.append("        is_satisfied=result.is_valid,")
    lines.append("        details=result.reason,")
    lines.append("        evaluated_at=datetime.utcnow(),")
    lines.append("    )")
    lines.append("")

    return "\n".join(lines)


def generate_documentation() -> str:
    """Generate src/rules/documentation.py from documentation.yaml."""
    data = load_yaml("documentation")
    version = data.get("version", "unknown")
    lines = [header("documentation.yaml", version)]

    lines.append('"""Documentation and certification requirement validators.')
    lines.append("")
    lines.append("Loaded from rules/generated/documentation.yaml. Encodes the required")
    lines.append("documentation/certification for each dispute condition as specified in")
    lines.append("Visa Core Rules Section 11.7-11.10.")
    lines.append('"""')
    lines.append("")
    lines.append("from dataclasses import dataclass")
    lines.append("from pathlib import Path")
    lines.append("from typing import Any")
    lines.append("")
    lines.append("import yaml")
    lines.append("")
    lines.append("from src.models.dispute import DisputeCase")
    lines.append("from src.models.enums import DisputeCondition, FraudTypeCode")
    lines.append("")
    lines.append("")
    lines.append("@dataclass")
    lines.append("class DocumentationRequirement:")
    lines.append('    """A required document or certification for a dispute condition."""')
    lines.append("")
    lines.append("    requirement_id: str")
    lines.append("    description: str")
    lines.append("    is_mandatory: bool")
    lines.append("    rule_section: str")
    lines.append("    condition: str")
    lines.append("")
    lines.append("")
    lines.append("@dataclass")
    lines.append("class DocumentationCheckResult:")
    lines.append('    """Result of checking documentation requirements."""')
    lines.append("")
    lines.append("    is_complete: bool")
    lines.append("    met_requirements: list[str]")
    lines.append("    missing_requirements: list[str]")
    lines.append("    details: str")
    lines.append("")
    lines.append("")
    lines.append("# Load documentation rules from YAML at import time")
    lines.append('_YAML_PATH = Path(__file__).resolve().parent.parent.parent / "rules" / "generated" / "documentation.yaml"')
    lines.append('with open(_YAML_PATH, encoding="utf-8") as _f:')
    lines.append("    _DOC_DATA: dict[str, Any] = yaml.safe_load(_f)")
    lines.append("")
    lines.append("")
    lines.append("def _build_requirements() -> dict[DisputeCondition, list[DocumentationRequirement]]:")
    lines.append('    """Build the DOCUMENTATION_REQUIREMENTS dict from YAML data."""')
    lines.append("    result: dict[DisputeCondition, list[DocumentationRequirement]] = {}")
    lines.append('    for cond_code, reqs in _DOC_DATA.get("requirements", {}).items():')
    lines.append("        try:")
    lines.append("            condition = DisputeCondition(cond_code)")
    lines.append("        except ValueError:")
    lines.append("            continue")
    lines.append("        result[condition] = [")
    lines.append("            DocumentationRequirement(")
    lines.append('                requirement_id=r["requirement_id"],')
    lines.append('                description=r["description"],')
    lines.append('                is_mandatory=r["is_mandatory"],')
    lines.append('                rule_section=r["rule_section"],')
    lines.append("                condition=cond_code,")
    lines.append("            )")
    lines.append("            for r in reqs")
    lines.append("        ]")
    lines.append("    return result")
    lines.append("")
    lines.append("")
    lines.append("DOCUMENTATION_REQUIREMENTS = _build_requirements()")
    lines.append("")
    lines.append("")
    lines.append("def _build_letter_requirements() -> tuple[list[str], list[str]]:")
    lines.append('    """Build cardholder letter requirements from YAML data."""')
    lines.append('    letter_reqs = _DOC_DATA.get("cardholder_letter_requirements", {})')
    lines.append('    cat_10 = letter_reqs.get("category_10", [])')
    lines.append('    cat_13 = letter_reqs.get("category_13", [])')
    lines.append("    return cat_10, cat_13")
    lines.append("")
    lines.append("")
    lines.append("CATEGORY_10_LETTER_REQUIREMENTS, CATEGORY_13_LETTER_REQUIREMENTS = _build_letter_requirements()")
    lines.append("")
    lines.append("")
    lines.append("def _build_fraud_code_requirements() -> dict[DisputeCondition, list[FraudTypeCode]]:")
    lines.append('    """Build fraud type code requirements from YAML data."""')
    lines.append("    result: dict[DisputeCondition, list[FraudTypeCode]] = {}")
    lines.append('    for cond_code, req_data in _DOC_DATA.get("fraud_type_code_requirements", {}).items():')
    lines.append("        try:")
    lines.append("            condition = DisputeCondition(cond_code)")
    lines.append("        except ValueError:")
    lines.append("            continue")
    lines.append('        result[condition] = [FraudTypeCode(c) for c in req_data["allowed_codes"]]')
    lines.append("    return result")
    lines.append("")
    lines.append("")
    lines.append("_FRAUD_CODE_REQUIREMENTS = _build_fraud_code_requirements()")
    lines.append("")
    lines.append("")

    # check_fraud_type_code_requirement function
    lines.append("def check_fraud_type_code_requirement(case: DisputeCase) -> DocumentationCheckResult:")
    lines.append('    """Check that the correct fraud type code was reported for Category 10 conditions.')
    lines.append("")
    lines.append("    Per Section 11.7.2.2: Before initiating a Dispute, an Issuer must report")
    lines.append("    the Fraud Activity to Visa using the appropriate fraud type code.")
    lines.append('    """')
    lines.append("    if case.condition is None:")
    lines.append("        return DocumentationCheckResult(")
    lines.append("            is_complete=False,")
    lines.append("            met_requirements=[],")
    lines.append('            missing_requirements=["dispute_condition_not_assigned"],')
    lines.append('            details="Cannot check fraud type code: no dispute condition assigned",')
    lines.append("        )")
    lines.append("")
    lines.append("    if case.condition not in _FRAUD_CODE_REQUIREMENTS:")
    lines.append("        return DocumentationCheckResult(")
    lines.append("            is_complete=True,")
    lines.append('            met_requirements=["no_fraud_code_required"],')
    lines.append("            missing_requirements=[],")
    lines.append('            details="No specific fraud type code required for this condition",')
    lines.append("        )")
    lines.append("")
    lines.append("    allowed = _FRAUD_CODE_REQUIREMENTS[case.condition]")
    lines.append("    if case.fraud_type_code is None:")
    lines.append("        return DocumentationCheckResult(")
    lines.append("            is_complete=False,")
    lines.append("            met_requirements=[],")
    lines.append('            missing_requirements=["fraud_type_code"],')
    lines.append('            details=f"Fraud type code not reported. Required: {[c.value for c in allowed]}",')
    lines.append("        )")
    lines.append("")
    lines.append("    if case.fraud_type_code in allowed:")
    lines.append("        return DocumentationCheckResult(")
    lines.append("            is_complete=True,")
    lines.append('            met_requirements=["fraud_type_code"],')
    lines.append("            missing_requirements=[],")
    lines.append('            details=f"Correct fraud type code reported: {case.fraud_type_code.value}",')
    lines.append("        )")
    lines.append("")
    lines.append("    return DocumentationCheckResult(")
    lines.append("        is_complete=False,")
    lines.append("        met_requirements=[],")
    lines.append('        missing_requirements=["fraud_type_code_mismatch"],')
    lines.append("        details=(")
    lines.append('            f"Incorrect fraud type code: {case.fraud_type_code.value}. "')
    lines.append('            f"Required: {[c.value for c in allowed]}"')
    lines.append("        ),")
    lines.append("    )")
    lines.append("")
    lines.append("")

    # check_documentation_requirements function
    lines.append("def check_documentation_requirements(case: DisputeCase) -> DocumentationCheckResult:")
    lines.append('    """Check all documentation requirements for a dispute case."""')
    lines.append("    if case.condition is None:")
    lines.append("        return DocumentationCheckResult(")
    lines.append("            is_complete=False,")
    lines.append("            met_requirements=[],")
    lines.append('            missing_requirements=["condition_not_assigned"],')
    lines.append('            details="Cannot check documentation: no dispute condition assigned",')
    lines.append("        )")
    lines.append("")
    lines.append("    requirements = DOCUMENTATION_REQUIREMENTS.get(case.condition, [])")
    lines.append("    if not requirements:")
    lines.append("        return DocumentationCheckResult(")
    lines.append("            is_complete=True,")
    lines.append("            met_requirements=[],")
    lines.append("            missing_requirements=[],")
    lines.append('            details=f"No specific documentation requirements for {case.condition.value}",')
    lines.append("        )")
    lines.append("")
    lines.append("    met: list[str] = []")
    lines.append("    missing: list[str] = []")
    lines.append("")
    lines.append("    has_certification = case.issuer_certification is not None")
    lines.append("    has_cardholder_letter = case.cardholder.signed_letter_provided")
    lines.append("    has_evidence = len(case.evidence) > 0")
    lines.append("")
    lines.append("    for req in requirements:")
    lines.append("        if not req.is_mandatory:")
    lines.append("            continue")
    lines.append("")
    lines.append('        if "certification" in req.description.lower() or "certif" in req.requirement_id:')
    lines.append("            if has_certification or has_cardholder_letter:")
    lines.append("                met.append(req.requirement_id)")
    lines.append("            else:")
    lines.append("                missing.append(req.requirement_id)")
    lines.append('        elif "fraud" in req.requirement_id.lower() and "report" in req.requirement_id.lower():')
    lines.append("            if case.fraud_type_code is not None:")
    lines.append("                met.append(req.requirement_id)")
    lines.append("            else:")
    lines.append("                missing.append(req.requirement_id)")
    lines.append("        elif has_evidence:")
    lines.append("            met.append(req.requirement_id)")
    lines.append("        else:")
    lines.append("            missing.append(req.requirement_id)")
    lines.append("")
    lines.append("    is_complete = len(missing) == 0")
    lines.append("")
    lines.append("    return DocumentationCheckResult(")
    lines.append("        is_complete=is_complete,")
    lines.append("        met_requirements=met,")
    lines.append("        missing_requirements=missing,")
    lines.append("        details=(")
    lines.append('            f"Documentation check: {len(met)} met, {len(missing)} missing"')
    lines.append("            if missing")
    lines.append('            else "All documentation requirements met"')
    lines.append("        ),")
    lines.append("    )")
    lines.append("")

    return "\n".join(lines)


def generate_compelling_evidence() -> str:
    """Generate src/rules/compelling_evidence.py from compelling_evidence.yaml."""
    data = load_yaml("compelling_evidence")
    version = data.get("version", "unknown")
    lines = [header("compelling_evidence.yaml", version)]

    lines.append('"""Compelling evidence evaluation logic.')
    lines.append("")
    lines.append("Loaded from rules/generated/compelling_evidence.yaml.")
    lines.append("Implements Visa Core Rules Section 11.5.2.")
    lines.append('"""')
    lines.append("")
    lines.append("from dataclasses import dataclass")
    lines.append("from datetime import datetime")
    lines.append("from pathlib import Path")
    lines.append("from typing import Any")
    lines.append("")
    lines.append("import yaml")
    lines.append("")
    lines.append("from src.models.dispute import DisputeCase, DisputeEvidence, RuleEvaluationResult")
    lines.append("from src.models.enums import DisputeCondition")
    lines.append("")
    lines.append("")
    lines.append("@dataclass")
    lines.append("class CompellingEvidenceResult:")
    lines.append('    """Result of compelling evidence evaluation."""')
    lines.append("")
    lines.append("    is_compelling: bool")
    lines.append("    evidence_type: str")
    lines.append("    description: str")
    lines.append("    rule_section: str")
    lines.append("")
    lines.append("")
    lines.append("# Load compelling evidence rules from YAML at import time")
    lines.append('_YAML_PATH = Path(__file__).resolve().parent.parent.parent / "rules" / "generated" / "compelling_evidence.yaml"')
    lines.append('with open(_YAML_PATH, encoding="utf-8") as _f:')
    lines.append("    _CE_DATA: dict[str, Any] = yaml.safe_load(_f)")
    lines.append("")
    lines.append("")
    lines.append("def _build_evidence_types() -> dict[DisputeCondition, list[dict[str, str]]]:")
    lines.append('    """Build COMPELLING_EVIDENCE_TYPES from YAML data."""')
    lines.append("    result: dict[DisputeCondition, list[dict[str, str]]] = {}")
    lines.append('    for cond_code, evidence_list in _CE_DATA.get("evidence_types", {}).items():')
    lines.append("        try:")
    lines.append("            condition = DisputeCondition(cond_code)")
    lines.append("        except ValueError:")
    lines.append("            continue")
    lines.append("        result[condition] = evidence_list")
    lines.append("    return result")
    lines.append("")
    lines.append("")
    lines.append("def _build_keyword_mappings() -> dict[str, list[str]]:")
    lines.append('    """Build keyword mappings from YAML data."""')
    lines.append('    return _CE_DATA.get("keyword_mappings", {})')
    lines.append("")
    lines.append("")
    lines.append("COMPELLING_EVIDENCE_TYPES = _build_evidence_types()")
    lines.append("_TYPE_KEYWORDS = _build_keyword_mappings()")
    lines.append("")
    lines.append("")
    lines.append("def evaluate_compelling_evidence(")
    lines.append("    case: DisputeCase,")
    lines.append("    acquirer_evidence: list[DisputeEvidence],")
    lines.append(") -> list[CompellingEvidenceResult]:")
    lines.append('    """Evaluate whether acquirer-provided evidence qualifies as compelling."""')
    lines.append("    results: list[CompellingEvidenceResult] = []")
    lines.append("")
    lines.append("    if case.condition is None:")
    lines.append("        results.append(")
    lines.append("            CompellingEvidenceResult(")
    lines.append("                is_compelling=False,")
    lines.append('                evidence_type="none",')
    lines.append('                description="No dispute condition assigned; cannot evaluate compelling evidence",')
    lines.append('                rule_section="11.5.2",')
    lines.append("            )")
    lines.append("        )")
    lines.append("        return results")
    lines.append("")
    lines.append("    allowed_types = COMPELLING_EVIDENCE_TYPES.get(case.condition, [])")
    lines.append("    if not allowed_types:")
    lines.append("        results.append(")
    lines.append("            CompellingEvidenceResult(")
    lines.append("                is_compelling=False,")
    lines.append('                evidence_type="not_applicable",')
    lines.append('                description=f"No compelling evidence types defined for condition {case.condition.value}",')
    lines.append('                rule_section="11.5.2",')
    lines.append("            )")
    lines.append("        )")
    lines.append("        return results")
    lines.append("")
    lines.append("    for evidence in acquirer_evidence:")
    lines.append("        if not evidence.is_compelling_evidence:")
    lines.append("            continue")
    lines.append("")
    lines.append("        matched = False")
    lines.append("        for allowed in allowed_types:")
    lines.append('            if _evidence_matches_type(evidence, allowed["type"]):')
    lines.append("                results.append(")
    lines.append("                    CompellingEvidenceResult(")
    lines.append("                        is_compelling=True,")
    lines.append("                        evidence_type=allowed[\"type\"],")
    lines.append("                        description=f\"Evidence matches: {allowed['description']}\",")
    lines.append("                        rule_section=allowed[\"rule_section\"],")
    lines.append("                    )")
    lines.append("                )")
    lines.append("                matched = True")
    lines.append("                break")
    lines.append("")
    lines.append("        if not matched:")
    lines.append("            results.append(")
    lines.append("                CompellingEvidenceResult(")
    lines.append("                    is_compelling=False,")
    lines.append("                    evidence_type=evidence.evidence_type,")
    lines.append("                    description=f\"Evidence type '{evidence.evidence_type}' does not match any compelling evidence criteria\",")
    lines.append('                    rule_section="11.5.2",')
    lines.append("                )")
    lines.append("            )")
    lines.append("")
    lines.append("    if not results:")
    lines.append("        results.append(")
    lines.append("            CompellingEvidenceResult(")
    lines.append("                is_compelling=False,")
    lines.append('                evidence_type="none_provided",')
    lines.append('                description="No compelling evidence was provided by the acquirer",')
    lines.append('                rule_section="11.5.2",')
    lines.append("            )")
    lines.append("        )")
    lines.append("")
    lines.append("    return results")
    lines.append("")
    lines.append("")
    lines.append("def _evidence_matches_type(evidence: DisputeEvidence, evidence_type: str) -> bool:")
    lines.append('    """Check if a piece of evidence matches a compelling evidence type."""')
    lines.append("    type_lower = evidence.evidence_type.lower()")
    lines.append("    desc_lower = evidence.description.lower()")
    lines.append("")
    lines.append("    keywords = _TYPE_KEYWORDS.get(evidence_type, [])")
    lines.append("    return any(keyword in type_lower or keyword in desc_lower for keyword in keywords)")
    lines.append("")
    lines.append("")
    lines.append("def convert_to_rule_evaluation(result: CompellingEvidenceResult) -> RuleEvaluationResult:")
    lines.append('    """Convert a compelling evidence result to a rule evaluation for recording."""')
    lines.append("    return RuleEvaluationResult(")
    lines.append('        rule_id=f"compelling_evidence_{result.evidence_type}",')
    lines.append("        rule_section=result.rule_section,")
    lines.append("        rule_description=result.description,")
    lines.append("        is_satisfied=result.is_compelling,")
    lines.append("        details=result.description,")
    lines.append("        evaluated_at=datetime.utcnow(),")
    lines.append("    )")
    lines.append("")

    return "\n".join(lines)


def generate_categorizer() -> str:
    """Generate the YAML-loading portion for src/rules/categorizer.py.

    The categorizer uses AI (OpenAI) for actual categorization, so we only
    inject the keyword lists from YAML. The AI categorization logic remains.
    """
    data = load_yaml("categorizer")
    version = data.get("version", "unknown")

    # We don't fully regenerate categorizer.py since it has AI logic.
    # Instead we generate a helper module that provides the keyword data.
    lines = [header("categorizer.yaml", version)]

    lines.append('"""Categorizer keyword data loaded from rules/generated/categorizer.yaml.')
    lines.append("")
    lines.append("Provides keyword lists and category metadata for dispute categorization.")
    lines.append('"""')
    lines.append("")
    lines.append("from pathlib import Path")
    lines.append("from typing import Any")
    lines.append("")
    lines.append("import yaml")
    lines.append("")
    lines.append("")
    lines.append("# Load categorizer data from YAML at import time")
    lines.append('_YAML_PATH = Path(__file__).resolve().parent.parent.parent / "rules" / "generated" / "categorizer.yaml"')
    lines.append('with open(_YAML_PATH, encoding="utf-8") as _f:')
    lines.append("    _CAT_DATA: dict[str, Any] = yaml.safe_load(_f)")
    lines.append("")
    lines.append('FRAUD_INDICATORS: list[str] = _CAT_DATA.get("fraud_indicators", [])')
    lines.append('AUTHORIZATION_INDICATORS: list[str] = _CAT_DATA.get("authorization_indicators", [])')
    lines.append('PROCESSING_ERROR_INDICATORS: list[str] = _CAT_DATA.get("processing_error_indicators", [])')
    lines.append('CATEGORIES: dict[str, Any] = _CAT_DATA.get("categories", {})')
    lines.append("")

    return "\n".join(lines)


def _condition_enum_map() -> dict[str, str]:
    """Map condition codes to their DisputeCondition enum names."""
    return {
        "10.1": "EMV_COUNTERFEIT_FRAUD",
        "10.2": "EMV_NON_COUNTERFEIT_FRAUD",
        "10.3": "OTHER_FRAUD_CARD_PRESENT",
        "10.4": "OTHER_FRAUD_CARD_ABSENT",
        "10.5": "VISA_FRAUD_MONITORING",
        "11.1": "CARD_RECOVERY_BULLETIN",
        "11.2": "DECLINED_AUTHORIZATION",
        "11.3": "NO_AUTHORIZATION",
        "12.2": "INCORRECT_TRANSACTION_CODE",
        "12.3": "INCORRECT_CURRENCY",
        "12.4": "INCORRECT_ACCOUNT_NUMBER",
        "12.5": "INCORRECT_AMOUNT",
        "12.6": "DUPLICATE_PROCESSING",
        "12.7": "INVALID_DATA",
        "13.1": "MERCHANDISE_NOT_RECEIVED",
        "13.2": "CANCELLED_RECURRING",
        "13.3": "NOT_AS_DESCRIBED",
        "13.4": "COUNTERFEIT_MERCHANDISE",
        "13.5": "MISREPRESENTATION",
        "13.6": "CREDIT_NOT_PROCESSED",
        "13.7": "CANCELLED_MERCHANDISE",
        "13.8": "OCT_NOT_ACCEPTED",
        "13.9": "NON_RECEIPT_CASH_ATM",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Python rule files from YAML schemas")
    parser.add_argument("--check", action="store_true", help="Check if files are up to date (exit 1 if not)")
    args = parser.parse_args()

    generators = {
        "time_limits": generate_time_limits,
        "validity": generate_validity,
        "documentation": generate_documentation,
        "compelling_evidence": generate_compelling_evidence,
        "categorizer_data": generate_categorizer,
    }

    all_up_to_date = True
    for name, generator in generators.items():
        content = generator()
        output_path = RULES_DIR / f"{name}.py"

        if args.check:
            if output_path.exists():
                existing = output_path.read_text(encoding="utf-8")
                if existing != content:
                    print(f"OUT OF DATE: {output_path}")
                    all_up_to_date = False
                else:
                    print(f"Up to date: {output_path}")
            else:
                print(f"MISSING: {output_path}")
                all_up_to_date = False
        else:
            output_path.write_text(content, encoding="utf-8")
            print(f"Generated {output_path}")

    if args.check and not all_up_to_date:
        sys.exit(1)


if __name__ == "__main__":
    main()
